# Generated by Django 4.0.2 on 2022-03-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_icon', models.CharField(blank=True, max_length=50)),
                ('contact_title', models.CharField(blank=True, max_length=50)),
                ('contact_desc', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
