# Generated by Django 4.0.2 on 2022-03-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
