# Generated by Django 4.0.2 on 2022-03-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_logo', models.ImageField(upload_to='')),
                ('home_name', models.CharField(max_length=50)),
                ('home_desc', models.TextField()),
                ('home_skill', models.CharField(max_length=100)),
                ('home_loction', models.CharField(max_length=100)),
            ],
        ),
    ]
