# Generated by Django 4.0.2 on 2022-03-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='socialmedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_plateform', models.CharField(max_length=50)),
                ('social_url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='home',
            name='home_logo',
            field=models.ImageField(upload_to=None, verbose_name='logo'),
        ),
    ]
