# Generated by Django 4.0.2 on 2022-03-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_socialmedia_alter_home_home_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='social_url',
            field=models.CharField(max_length=250),
        ),
    ]
