# Generated by Django 4.0.2 on 2022-03-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_socialmedia_social_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='social_url',
            field=models.URLField(max_length=250),
        ),
    ]
