# Generated by Django 4.0.2 on 2022-03-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_socialmedia_social_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='home_logo',
            field=models.ImageField(upload_to='static/img/', verbose_name='/static/img/'),
        ),
    ]
