# Generated by Django 4.0.2 on 2022-03-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_home_home_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='home_logo',
            field=models.ImageField(upload_to='static/img/', verbose_name=''),
        ),
    ]
