# Generated by Django 4.0.2 on 2022-03-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_home_home_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='home_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='home_loction',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='home',
            name='home_logo',
            field=models.ImageField(blank=True, upload_to='static/img', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='home',
            name='home_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='home',
            name='home_skill',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='social_plateform',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='social_url',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
