# Generated by Django 4.0.2 on 2022-03-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infom', models.CharField(max_length=50)),
                ('abouts', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('subheading', models.TextField()),
            ],
        ),
    ]
