# Generated by Django 4.0.2 on 2022-03-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='about',
        ),
        migrations.AddField(
            model_name='heading',
            name='abouts',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
