# Generated by Django 4.0.2 on 2022-03-07 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_delete_about_heading_abouts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heading',
            name='subheading',
        ),
    ]
