# Generated by Django 4.0.2 on 2022-03-07 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_remove_heading_subheading'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='heading',
            new_name='about',
        ),
    ]
