# Generated by Django 4.0.2 on 2022-03-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_rename_heading_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='infomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('detail_name', models.CharField(max_length=50)),
            ],
        ),
    ]
