# Generated by Django 4.0.2 on 2022-03-08 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_infomation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='infomation',
            new_name='information',
        ),
    ]
