# Generated by Django 4.0.2 on 2022-03-08 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_rename_infomation_information'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='information',
            new_name='informati',
        ),
    ]
