# Generated by Django 4.0.2 on 2022-03-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_rename_information_informati'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='abouts',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='heading',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='informati',
            name='detail_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='informati',
            name='field_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
