# Generated by Django 4.0.2 on 2022-03-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enddate', models.DateField(auto_created=True, blank=True)),
                ('startdate', models.DateField(auto_created=True, blank=True)),
                ('Degree', models.CharField(blank=True, max_length=50)),
                ('univercity', models.CharField(blank=True, max_length=250)),
                ('acitvies', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(auto_created=True, blank=True)),
                ('desination', models.CharField(blank=True, max_length=50)),
                ('enddate', models.DateField(blank=True)),
                ('companyname', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
