# Generated by Django 4.0.2 on 2022-03-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='enddate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='startdate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='startdate',
            field=models.DateField(blank=True),
        ),
    ]
