# Generated by Django 4.0.2 on 2022-03-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_education_enddate_alter_education_startdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
            ],
        ),
    ]
