# Generated by Django 4.0.2 on 2022-03-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_icon', models.CharField(blank=True, max_length=50)),
                ('count_numb', models.IntegerField(blank=True, max_length=10)),
                ('count_decs', models.CharField(blank=True, max_length=25)),
            ],
        ),
    ]
