# Generated by Django 4.0.2 on 2022-03-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='skil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, max_length=25)),
                ('score', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='count',
            name='count_numb',
            field=models.IntegerField(blank=True),
        ),
    ]
